In [1]:
import scanpy as sc
import anndata
import git
import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.sparse import csr_matrix

git_repo = git.Repo(".", search_parent_directories=True)
git_root = git_repo.git.rev_parse("--show-toplevel")

In [2]:
inter = os.path.join(git_root, "raw_data", "Pasca_scRNAseq", "inter")
inter_test = os.path.join(git_root, "raw_data", "Pasca_scRNAseq", "inter-test")

pasca_aggr_old_path = os.path.join(inter, "pasca_aggr.h5ad")
pasca_aggr_new_path = os.path.join(inter_test, "pasca_aggr.h5ad")

pasca_preqc_old_path = os.path.join(inter, "pasca_preqc.h5ad")
pasca_preqc_new_path = os.path.join(inter_test, "pasca_preqc.h5ad")

pasca_postqc_old_path = os.path.join(inter, "pasca_postqc.h5ad")
pasca_postqc_new_path = os.path.join(inter_test, "pasca_postqc.h5ad")

pasca_log1p_old_path = os.path.join(inter, "pasca_log1p.h5ad")
pasca_log1p_new_path = os.path.join(inter_test, "pasca_log1p.h5ad")

In [3]:
pasca_aggr_old = anndata.read(pasca_aggr_old_path)
pasca_aggr_new = anndata.read(pasca_aggr_new_path)

pasca_preqc_old = anndata.read(pasca_preqc_old_path)
pasca_preqc_new = anndata.read(pasca_preqc_new_path)

pasca_postqc_old = anndata.read(pasca_postqc_old_path)
pasca_postqc_new = anndata.read(pasca_postqc_new_path)

pasca_log1p_old = anndata.read(pasca_log1p_old_path)
pasca_log1p_new = anndata.read(pasca_log1p_new_path)

In [4]:
assert pasca_aggr_old.X.shape == pasca_aggr_old.X.shape
assert pasca_preqc_old.X.shape == pasca_preqc_old.X.shape
assert pasca_postqc_old.X.shape == pasca_postqc_old.X.shape
assert pasca_log1p_old.X.shape == pasca_log1p_old.X.shape

In [5]:
adata1 = sc.read_10x_mtx('../../raw_data/Pasca_scRNAseq/raw/GSM4306931_Control_1',var_names='gene_symbols',cache=True, gex_only=True)
adata2 = sc.read_10x_mtx('../../raw_data/Pasca_scRNAseq/raw/GSM4306932_Control_2',var_names='gene_symbols',cache=True, gex_only=True)
adata3 = sc.read_10x_mtx('../../raw_data/Pasca_scRNAseq/raw/GSM4306933_Patient_1',var_names='gene_symbols',cache=True, gex_only=True)
adata4 = sc.read_10x_mtx('../../raw_data/Pasca_scRNAseq/raw/GSM4306934_Patient_2',var_names='gene_symbols',cache=True, gex_only=True)
adata = adata1.concatenate(adata2,adata3,adata4)
adata.X = csr_matrix(adata.X)

/Users/darvesh/opt/anaconda3/envs/scrna/lib/python3.10/site-packages/anndata/_core/anndata.py:1785: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  [AnnData(sparse.csr_matrix(a.shape), obs=a.obs) for a in all_adatas],


In [6]:
array0 = adata.X.toarray()
array1 = pasca_aggr_old.X.toarray()
array2 = pasca_aggr_new.X.toarray()

In [7]:
array0_nonzero = np.nonzero(array0)
array1_nonzero = np.nonzero(array1)
array2_nonzero = np.nonzero(array2)

In [8]:
array0_nonzero

(array([    0,     0,     0, ..., 45299, 45299, 45299]),
 array([   17,    18,    26, ..., 33503, 33504, 33505]))

In [9]:
array1_nonzero

(array([    0,     0,     0, ..., 45299, 45299, 45299]),
 array([   17,    18,    26, ..., 33503, 33504, 33505]))

In [10]:
array2_nonzero

(array([    0,     0,     0, ..., 45299, 45299, 45299]),
 array([   17,    18,    26, ..., 33503, 33504, 33505]))

In [ ]:
np.array_equal(array0, array2)